name: 'Terraform'

on:
  push:
    branches: [ "develop" ]
  fork:
     types:
     runs-on: ubuntu-latest
     env:AWS_REGION: ap-south-1 
     
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ''
          aws-secret-access-key: '
      
      - name: initialize terraform
        run: terraform init
      
      - name: terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
    
      - name: terraform apply
        run: terraform apply
        
